config/routes.rb
Rails.application.routes.draw do
  
  # 顧客用
  # URL /users/sign_in ...
  devise_for :users, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }
  
  scope module: :public do
    root to: "homes#top"
    resources :post_images, only: [:new, :create, :show, :index, :destroy] do
      resource :favorite, only: [:create, :destroy]
      resources :comments, only: [:create, :destroy]
    end
    
    get "search" => "searches#search"
    get '/genre/search' => 'searches#genre_search'
    get "users/check" => "users#check"
    patch "users/withdraw" => "users#withdraw"
    
    resources :users, only: [:show, :edit, :update] do
      resource :relationships, only: [:create, :destroy]
      get 'followings' => 'relationships#followings', as: 'followings'
      get 'followers' => 'relationships#followers', as: 'followers'
      member do
      # いいねした一覧
        get :liked_posts
      end
    end
  end
  
  namespace :admin do
    resources :genres, only: [:create, :index, :edit, :update, :destroy]
    resources :users, only: [:show, :index, :edit, :update]
    
    root to: "homes#top"
    get "search" => "searches#search"
  end
  
  devise_scope :user do
    post "users/guest_sign_in", to: "public/sessions#guest_sign_in"
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
end

app/controllers/admin/searches_controller.rb
class Admin::SearchesController < ApplicationController
  before_action :authenticate_admin!
  
  def search
    @model = params[:model]
    @content = params[:content]
    @method = params[:method]
    
    # 選択したモデルに応じて検索を実行
    if @model  == "user"
      @records = User.search_for(@content, @method)
    end
  end
end

app/helpers/admin/searches_helper.rb
module Admin::SearchesHelper
end

app/views/admin/searches/_admin_searchform.html.erb
<%= form_with url: admin_search_path, method: :get, local: true do |f| %>
    <%= f.text_field :content %>
    <%= f.select :model, options_for_select({"ユーザー" => "user"}) %>
    <%= f.select :method, options_for_select({"完全一致" => "perfect", "前方一致" => "forward", "後方一致" => "backward", "部分一致" => "partial"}) %>
    <%= f.submit "検索" %>
  <% end %>

app/views/admin/searches/search.html.erb
<div class="container">
<label class="h4 bg-light mt-2 px-4">"<%= @content %>"の検索結果</label>
  <div class="row">
    <div class="col-lg-2"></div>
    <div class="col-lg-10">
      <% if @model == 'user' %>
        <%= render 'admin/users/admin_index', users: @records %>
      <% end %>
    </div>
  </div>
</div>