config/routes.rb
Rails.application.routes.draw do
  
  # 顧客用
  # URL /users/sign_in ...
  devise_for :users, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }
  
  scope module: :public do
    root to: "homes#top"
    resources :post_images, only: [:new, :create, :show, :index, :destroy] do
      resource :favorite, only: [:create, :destroy]
      resources :comments, only: [:create, :destroy]
    end
    
    get "search" => "searches#search"
    get '/genre/search' => 'searches#genre_search'
    get "users/check" => "users#check"
    patch "users/withdraw" => "users#withdraw"
    
    resources :users, only: [:show, :edit, :update] do
      resource :relationships, only: [:create, :destroy]
      get 'followings' => 'relationships#followings', as: 'followings'
      get 'followers' => 'relationships#followers', as: 'followers'
      member do
      # いいねした一覧
        get :liked_posts
      end
    end
  end
  
  namespace :admin do
    resources :genres, only: [:create, :index, :edit, :update, :destroy]
    resources :users, only: [:show, :index, :edit, :update]
    
    root to: "homes#top"
    get "search" => "searches#search"
  end
  
  devise_scope :user do
    post "users/guest_sign_in", to: "public/sessions#guest_sign_in"
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :post_images
  
  validates :name, presence: true
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  before_action :authenticate_admin!

  def index
    @genres = Genre.all
    @genre = Genre.new
  end

  def create
    @genre = Genre.new(genre_params)
    if @genre.save
      flash[:notice] = "登録に成功しました。"
      redirect_to admin_genres_path
    else
      flash.now[:alert] = "登録に失敗しました。"
      @genres = Genre.all
      @genre = Genre.new
      render :index
    end
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    if @genre.update(genre_params)
      flash[:notice] = "更新に成功しました。"
      redirect_to admin_genres_path
    else
      flash.now[:alert] = "更新に失敗しました。"
      render :edit
    end
  end

  def destroy
    genre = Genre.find(params[:id])
    if genre.destroy
      flash[:notice] = "削除に成功しました。"
      redirect_to admin_genres_path
    else
      flash.now[:alert] = "削除に失敗しました。"
      @genres = Genre.all
      @genre = Genre.new
      render :index
    end
  end

  private

  def genre_params
    params.require(:genre).permit(:name)
  end

end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/views/admin/genres/edit.html.erb
<div class="container">
  <label class="h4 bg-light mt-4 px-4">ジャンル編集</label>

  <div class="row">
    <div class="col-lg-10">
      
      <%= render 'layouts/errors', obj: @genre %>
      
      <div class="form mt-5 mb-5">
        <%= form_with model: @genre, url: admin_genre_path(@genre.id), method: :patch do |f| %>
          <%= f.label :ジャンル名, class:"mr-5" %>
          <%= f.text_field :name %>
          <%= f.submit '変更を保存', class:"btn btn-primary ml-5 px-4" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/admin/genres/index.html.erb
<div class="container">
  <label class="h4 bg-light mt-4 mb-5 px-4">ジャンル一覧・追加</label>
  <div class="row">
    <div class="col-lg-10">
      
      <%= render 'layouts/errors', obj: @genre %>
      
      <%= form_with model: @genre, url: admin_genres_path do |f| %>
        <%= f.label :ジャンル名, class:"mr-5" %>
        <%= f.text_field :name %>
        <%= f.submit '新規登録', class:"btn btn-primary ml-5" %>
      <% end %>
    </div>
  </div>

  <div class="row">
    <div class="col-lg-6">
      <table class="table shadow-sm mt-5">
        <thead class="bg-light">
          <th>ID</th>
          <th>ジャンル</th>
          <th colspan="2"></th>
        </thead>
        <tbody>
        <% @genres.each do |genre| %>
          <tr>
            <td><%= genre.id %></td>
            <td><%= genre.name %></td>
            <td><%= link_to "編集する", edit_admin_genre_path(genre.id), class:"btn btn-primary" %></td>
            <td><%= link_to "削除", admin_genre_path(genre.id), method: :delete, "data-confirm" => "本当に削除しますか？", class:"btn btn-danger" %></td>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>