config/routes.rb
Rails.application.routes.draw do
  
  # 顧客用
  # URL /users/sign_in ...
  devise_for :users, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }
  
  scope module: :public do
    root to: "homes#top"
    resources :post_images, only: [:new, :create, :show, :index, :destroy] do
      resource :favorite, only: [:create, :destroy]
      resources :comments, only: [:create, :destroy]
    end
    
    get "search" => "searches#search"
    get '/genre/search' => 'searches#genre_search'
    get "users/check" => "users#check"
    patch "users/withdraw" => "users#withdraw"
    
    resources :users, only: [:show, :edit, :update] do
      resource :relationships, only: [:create, :destroy]
      get 'followings' => 'relationships#followings', as: 'followings'
      get 'followers' => 'relationships#followers', as: 'followers'
      member do
      # いいねした一覧
        get :liked_posts
      end
    end
  end
  
  namespace :admin do
    resources :genres, only: [:create, :index, :edit, :update, :destroy]
    resources :users, only: [:show, :index, :edit, :update]
    
    root to: "homes#top"
    get "search" => "searches#search"
  end
  
  devise_scope :user do
    post "users/guest_sign_in", to: "public/sessions#guest_sign_in"
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :post_images, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  
   # フォローしている関連付け
  has_many :active_relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  # フォローされている関連付け
  has_many :passive_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  # フォローしているユーザーを取得
  has_many :followings, through: :active_relationships, source: :followed
  # フォロワーを取得
  has_many :followers, through: :passive_relationships, source: :follower
  
  validates :name, presence: true
  validates :account_name, presence: true
  validates :email, presence: true
  
  has_one_attached :profile_image
  
  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end
  
  def user_status
    if is_active == true
      "有効"
    else
      "退会"
    end
  end
  
  GUEST_USER_EMAIL = "guest@example.com"

  def self.guest
    find_or_create_by!(email: GUEST_USER_EMAIL) do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "guestuser"
      user.account_name = "guestuser"
    end
  end
  
  def guest_user?
    email == GUEST_USER_EMAIL
  end
  
  def self.search_for(content, method)
    if method == 'perfect'
      User.where(account_name: content)
    elsif method == 'forward'
      User.where('account_name LIKE ?', content + '%')
    elsif method == 'backward'
      User.where('account_name LIKE ?', '%' + content)
    else
      User.where('account_name LIKE ?', '%' + content + '%')
    end
  end
  
  # 指定したユーザーをフォローする
  def follow(user)
    active_relationships.create(followed_id: user.id)
  end
  # 指定したユーザーのフォローを解除する
  def unfollow(user)
    active_relationships.find_by(followed_id: user.id).destroy
  end
  # 指定したユーザーをフォローしているかどうかを判定
  def following?(user)
    followings.include?(user)
  end
  
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_admin!
  
  def index
    @users = User.page(params[:page])
  end

  def show
    @user = User.find(params[:id])
    @post_images = @user.post_images.page(params[:page])
  end

  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "更新に成功しました。"
      redirect_to admin_users_path
    else
      flash[:alert] = "更新に失敗しました。"
      render :edit
    end
  end
  
  private
  
  def user_params
    params.require(:user).permit(:profile_image, :name, :account_name, :email, :introduction, :is_active)
  end
  
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/admin/users/_admin_index.html.erb
<table class="table table shadow-sm">
  <thead class="bg-light">
    <tr>
      <th>会員ID</th>
      <th>アカウント名</th>
      <th>氏名</th>
      <th>メールアドレス</th>
      <th>ステータス</th>
    </tr>
  </thead>

  <tbody>
    <% users.each do |user| %>
    <tr>
      <td><%= user.id %></td>
      <td><%= user.account_name %></td>
      <td><%= link_to user.name, admin_user_path(user.id) %></td>
      <td><%= user.email %></td>
      <td>
        <% if user.is_active == true %>
          <p class="text-success">有効</p>
        <% else %>
          <p class="text-muted">退会</p>
        <% end %>
      </td>
    </tr>
    <% end %>
    </tbody>
  </table>

app/views/admin/users/edit.html.erb
<div class="container">
  <label class="h4 bg-light px-4">
    <%= @user.name %>さんの会員情報編集
  </label>
  <dvi class="row mb-2">
    <div class="col-lg-1"></div>
    <div class="col-lg-11">
      
      <%= render 'layouts/errors', obj: @user %>
      
      <%= form_with model: @user, url: admin_user_path(@user), local:true do |f| %>
        
        <div class="field">
          <%= f.label :"氏名" %><br />
          <%= f.text_field :name %> 
        </div>
        
        <div class="field">
          <%= f.label :"アカウント名" %><br />
          <%= f.text_field :account_name %> 
        </div>
            
        <div class="field">
          <%= f.label :"プロフィール画像" %><br />
          <%= f.file_field :profile_image, placeholder: "プロフィール画像", accept: "image/*" %>
        </div>
            
        <div class="field">
          <%= f.label :"紹介文" %><br />
          <%= f.text_area :introduction, class: "form-control", size: "5x5" %>
        </div>
            
        <div class="field">
          <%= f.label :"Eメール" %><br />
          <%= f.email_field :email, autofocus: true, autocomplete: "email", class: "form-control", size: "20x10" %>
        </div>
        
        <div class="field"><!--ラジオボックスで作成-->
          <%= f.label :"アカウントステータス" %><br />
          <%= f.radio_button :is_active, true %>有効
      　　  <%= f.radio_button :is_active, false %>退会
        </div>

        <div class="actions mt-3">
          <%= f.submit "変更を保存", class: "btn btn-primary px-5" %>
        </div>
      　　
      <% end %>
    </div>
  </div>
</div>

app/views/admin/users/index.html.erb
<div class="container">
  <div class="row mb-2">
    <div class="col-lg-2"></div>
    <div class="col-lg-10">
      <label class="h4 bg-light px-4">会員一覧</label>
    </div>
  </div>
  <div class="row mb-2">
    <div class="col-lg-2"></div>
    <div class="col-lg-8">
      <%= render "admin/users/admin_index", users: @users %>
    </div>
    <div class="col-lg-2"></div>
  </div>
  <div class="row mb-2">
    <div class="col-lg-5"></div>
    <div class="col-lg-7">
      <%= paginate @users %>
    </div>
  </div>
</div>

app/views/admin/users/show.html.erb
<div class="container">
  <label class="h4 bg-light mt-2 mb-2 px-4"><%= @user.name %>さんの会員詳細</label>
  <div class="row mb-2">
    
    <div class="col-lg-4">
      <table class="table table-condensed">
        <tbody>
          <tr>
            <th>会員ID</th>
            <td><%= @user.id %></td>
          </tr>
          <tr>
            <th>氏名</th>
            <td><%= @user.name %></td>
          </tr>
          <tr>
            <th>ユーザー名</th>
            <td><%= @user.account_name %></td>
          </tr>
          <tr>
            <th>メールアドレス</th>
            <td><%= @user.email %></td>
          </tr>
          <tr>
            <th>紹介文</th>
            <td><%= @user.introduction %></td>
          </tr>
          <tr>
            <th>会員ステータス</th>
            <td>
              <% if @user.is_active == true %>
                <p class="text-success">有効</p>
              <% else %>
                <p class="text-muted">退会</p>
              <% end %>
            </td>
          </tr>
          <tr>
            <td><%= link_to "編集する", edit_admin_user_path(@user.id), class: "btn btn-sm btn-primary" %></td>
          </tr>
        </tbody>
      </table>
    </div>
    
    <div class="col-lg-8">
      <div class="d-flex flex-wrap">
        <% @user.post_images.each do |post_image| %>
          <div class="card m-2 shadow-lg">
              <%= image_tag post_image.get_image(300,300), class: "card-img-top"; %>
              <p class="ml-1"><strong><span class="text-dark"><%= post_image.name %></span></strong></p>
              <p class="text-dark ml-1">投稿日：<%= post_image.created_at.strftime('%Y/%m/%d') %></p>
              <span class="text-dark ml-1"> By <%= post_image.user.account_name %></span></br>
              <span class="text-dark mb-2">♥<%= post_image.favorites.count %> いいね | <%= post_image.comments.count %>コメント</span>
          </div>
        <% end %>
        <%= paginate @post_images %>
      </div>
    </div>
    
  </div>
</div>