config/routes.rb
Rails.application.routes.draw do
  
  # 顧客用
  # URL /users/sign_in ...
  devise_for :users, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }
  
  scope module: :public do
    root to: "homes#top"
    resources :post_images, only: [:new, :create, :show, :index, :destroy] do
      resource :favorite, only: [:create, :destroy]
      resources :comments, only: [:create, :destroy]
    end
    
    get "search" => "searches#search"
    get '/genre/search' => 'searches#genre_search'
    get "users/check" => "users#check"
    patch "users/withdraw" => "users#withdraw"
    
    resources :users, only: [:show, :edit, :update] do
      resource :relationships, only: [:create, :destroy]
      get 'followings' => 'relationships#followings', as: 'followings'
      get 'followers' => 'relationships#followers', as: 'followers'
      member do
      # いいねした一覧
        get :liked_posts
      end
    end
  end
  
  namespace :admin do
    resources :genres, only: [:create, :index, :edit, :update, :destroy]
    resources :users, only: [:show, :index, :edit, :update]
    
    root to: "homes#top"
    get "search" => "searches#search"
  end
  
  devise_scope :user do
    post "users/guest_sign_in", to: "public/sessions#guest_sign_in"
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
end

app/views/layouts/_errors.html.erb
<% if obj.errors.any? %>
  <div id="error_explanation">
    <h3><%= pluralize(obj.errors.count, "error") %> prohibited this obj from being saved:</h3>
    <ul>
      <% obj.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EachAging</title>
    <meta name="viewport" content="width=device-width,initial-scale=1, maximum-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="sticky-top">
      <nav class="navbar navbar-expand-lg navbar-dark bg-success">
        <div class="container">
          <a class="navbar-brand" href="/"><span>EachAging</span></a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                        aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
              <% if user_signed_in? %>
                <li class="nav-item text-light my-3 mr-5">
                  <%= "ようこそ、#{current_user.account_name}さん！" %>
                </li>
                <li>
                  <%= link_to 'マイページ', user_path(current_user), class: 'nav-link text-light' %>
                </li>
                <li>
                  <%= link_to '投稿一覧', post_images_path, class: 'nav-link text-light' %>
                </li>
                <li>
                  <%= link_to '投稿する', new_post_image_path, class: 'nav-link text-light' %>
                </li>
                <li>
                  <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'nav-link text-light' %>
                </li>
              <% elsif admin_signed_in? %>
                <li>
                  <%= link_to "会員一覧", admin_users_path, class: 'nav-link text-light' %>
                </li>
                <li>
                  <%= link_to "ジャンル一覧", admin_genres_path, class: 'nav-link text-light' %>
                </li>
                <li>
                  <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: 'nav-link text-light' %>
                </li>
              <% else %>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <main>
      <div class="d-flex justify-content-center mb-2">
        <% if user_signed_in? %>
          <%= render "public/searches/searchform" %>
        <% elsif admin_signed_in? %>
          <%= render "admin/searches/admin_searchform" %>
        <% else %>
        <% end %>
      </div>
      <% flash.each do |message_type, message| %>
        <div class="flash-message <%= message_type %>"><%= message %></div>
      <% end %>
    <%= yield %>
    </main>
    <footer class="bg-success text-light pt-3 pb-2">
      <div class="container">
        <div class="row">
          <div class="col-lg-4"></div>
          <div class="col-lg-8"><p>愛用品のそれぞれの経年変化を讃え合うSNS</p></div>
        </div>
      </div>
    </footer>
  </body>
</html>